.Dd May 17, 2025
.Dt GEARBOX 1
.Os
.Sh NAME
.Nm gearbox
.Nd non-interactive console client for transmission-daemon
.Sh SYNOPSIS
.Bk -words
.Bl -tag -width gearbox
.It Nm
.Op Fl H
.Op Fl h Ar host
.Op Fl p Ar port
.Oo Ar command
.Op Ar opt ...
.Op Ar arg ...
.Oc
.El
.Ek
.Sh DESCRIPTION
.Nm
is a non-interactive console client for
.Xr transmission-daemon 1
.Sh OPTIONS
The following options are supported by
.Nm :
.Bl -tag -width indent
.It Fl H
Display usage information and exit.
.It Fl h Ar host
Specify remote Transition server hostname or IP address to connect to.
See
.Sx Remote Address Resolution
section for more details.
.It Fl p Ar port
Specify remote Transition server TCP port to connect to.
See
.Sx Remote Address Resolution
section for more details.
.El
.Sh COMMANDS
The commands are supported by
.Nm :
.Bl -tag -width torrent
.It Xo
.Cm add
.Op Fl S
.Op Fl l Ar label[,label...]
.Ar file...
.Xc
Add torrent-file to the server.
Torrent is started for downloading by default.
.Pp
The options for
.Cm gearbox add
are as follows:
.Bl -tag -width Ds
.It Fl S
Do not start downloading torrent automatically.
.It Fl l Ar label[,label...]
Set labels to the added torrent.
.El
.It Xo
.Cm delete
.Op Fl d
.Ar id...
.Xc
Delete torrent.
.Pp
The options for
.Cm gearbox delete
are as follows:
.Bl -tag -width Ds
.It Fl d
Delete also torrent data.
.El
.It Xo
.Cm edit
.Op Fl l Ar label[,label...]
.Ar id...
.Xc
Edit torrent configurations.
.Pp
The options for
.Cm gearbox edit
are as follows:
.Bl -tag -width Ds
.It Fl l Ar label[,label...]
Assign labels to the torrent.
.El
.It Xo
.Cm info
.Op Fl fi
.Ar id...
.Xc
Display torrent information.
.Pp
The options for
.Cm gearbox info
are as follows:
.Bl -tag -width Ds
.It Fl f
Display files list represented by the torrent.
.It Fl i
Display torrent information, like its size, amount of transferred data and so
on.
.El
.It Xo
.Cm list
.Op Fl ar
.Op Fl c Ar column[,column...]
.Op Fl n Ar count
.Op Fl s Ar column
.Xc
List torrents managed by Transmission server.
.Pp
The options for
.Cm gearbox list
are as follows:
.Bl -tag -width Ds
.It Fl a
Display only active torrents.
Active torrent is the torrent which has at least one connected peer who
downloads or uploads torrent data.
.It Fl r
Sort torrents in reverse order.
.It Fl c Ar column[,column...]
List of columns to display. See
.Sx COLUMNS
section for the list of available columns.
.It Fl n Ar count
Maximum number of torrents to return in the result list.
.It Fl s Ar column
Column to sort result list by. See
.Sx COLUMNS
section for the list of available columns.
.El
.It Xo
.Cm start
.Ar id...
.Xc
Start downloading or seeding torrent.
.It Xo
.Cm stats
.Xc
Display server statistics.
.It Xo
.Cm stop
.Ar id...
.Xc
Stop (pause) torrent.
.Ss Remote Address Resolution
Hostname and port is used to connect to remote Transmission server can be
specified using
.Fl h
and
.Fl p
command-line options or using configuration file.
Command-line options have precedence over configuration file.
If hostname or port value is not defined on either level default value is used.
Default value for hostname is
.Ql localhost
and 9091 is for port.
See
.El
.Sh COLUMNS
List of column names which can be used to display torrent information or apply
sorting by.
.Bl -column "comment"
.It Li active Ta Last active time when torrent was downloaded or uploaded.
.It Li added Ta Time when torrent was added.
.It Li comment Ta Comment as specified in the torrent-file.
.It Li created Ta Time when torrent-file was created.
.It Li drate Ta Downloading rate.
.It Li dsize Ta Amount of data were downloaded for the torrent.
.It Li id Ta Transmission ID of the torrent.
.It Li labels Ta List of labels tagged to the torrent.
.It Li name Ta Name of the torrent.
.It Li ratio Ta Ratio between amount of uploaded and downloaded data for the torrent.
.It Li size Ta Size of the torrent data.
.It Li status Ta Status of the torrent. One of: stopped, queued for checking,
checking, queued for downloading, downloading, queued for seeding,
seeding.
.It Li urate Ta Uploading rate.
.It Li usize Ta Amount of data were uploaded for the torrent.
.El
.Sh CONFIGURATION
.Nm
configuration file is a plain text file containing property=value pairs, every on its
own line. Next list of properties is support.
.Bl -column "list-columns" "integer"
.It Sy Property Ta Sy Type Ta Sy Description
.It Li host Ta string Ta Remote hostname to connect to.
.It Li list-columns Ta string Ta Columns to print by list command.
.It Li list-count Ta integer Ta Number of columns to print by list command.
.It Li list-reverse Ta boolean Ta Reverse sorting order.
.It Li list-sort Ta string Ta Column to sort by in list command output.
.It Li port Ta integer Ta Remote port to connect to.
.El
.Pp
Configuration file example.
.Dl host = Qq transmission.local
.Dl port = 9091
.Dl list-columns = Qq id,status,size,ratio,name
.Dl list-sort = Qq added
.Dl list-reverse = true
.Sh FILES
.Bl -tag
.It Pa ~/.config/gearbox/gearbox.conf
Main
.Nm
configuration file.
See
.Sx CONFIGURATION
section for file format.
.El
.Sh EXAMPLES
List top ten torrents by ratio.
.Pp
.Dl $ gearbox list -c id,size,name -s ratio -r -n 10
.Pp
Add torrent and tag it with movie label.
.Pp
.Dl $ gearbox add -l movie file.torrent
.Sh SEE ALSO
.Xr  transmission-remote 1 ,
.Xr  transmission-daemon 1
.Sh AUTHORS
.An Viacheslav Chimishuk Aq Mt vchimishuk@yandex.ru
.Lk https://github.com/vchimishuk/gearbox
